ALTER TABLE ball_events
  ADD COLUMN IF NOT EXISTS penalty_reason TEXT NULL,
  ADD COLUMN IF NOT EXISTS penalty_to_fielding BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE innings
  ADD COLUMN IF NOT EXISTS bonus_runs INT NOT NULL DEFAULT 0;
